services:
  epochtal:
    image: ghcr.io/p2r3/epochtal:latest
    ports:
      - 8080:8080/tcp
    # Use environment values from the .env file.
    # If you don't want this, comment the following line and use the individual environment variables below instead.
    env_file: '.env'
    #environment:
    #  STEAM_API_KEY:
    #  DISCORD_API_KEY:
    #  JWT_SECRET:
    #  INTERNAL_SECRET:
    #  DISCORD_CHANNEL_ANNOUNCE:
    #  DISCORD_CHANNEL_REPORT:
    #  DISCORD_CHANNEL_UPDATE:
    # You can bind the data directory of epochtal to your host (recommended).
    # Comment out the following section if you don't want that.
    volumes:
      - <host-path>:/app/data
